import { SectionMediaItem } from "@/types/database";
import {
  FOOD_GALLERY_IMAGES,
  AMBIENCE_IMAGES,
  FARM_IMAGES,
  FEATURE_CARDS,
  CATEGORY_LINKS,
} from "@/lib/constants";

// Default fallback data for all sections (pure constants, safe for Client & Server)
export const DEFAULT_SECTION_MEDIA: Record<string, SectionMediaItem[]> = {
  hero: [
    {
      section_key: "hero",
      item_key: "hero_bg",
      title: "Hero Background",
      subtitle: "Brewing coffee, Brewing Experiences",
      image_url: "/assets/hero/hero-bg.webp",
      display_order: 1,
    },
  ],
  arrivals: [
    {
      section_key: "arrivals",
      item_key: "arrivals_dishes",
      title: "Mango Dish Collection",
      subtitle: "The Summer Affair featured seasonal collection",
      image_url: "/mango-dishes.png",
      display_order: 1,
    },
    {
      section_key: "arrivals",
      item_key: "arrivals_title",
      title: "The Summer Affair Title",
      subtitle: "Hand-lettered seasonal headline artwork",
      image_url: "/summer-affair-title-cropped.png",
      display_order: 2,
    },
    {
      section_key: "arrivals",
      item_key: "arrivals_branch",
      title: "Mango Branch Decoration",
      subtitle: "Top-right botanical ambience illustration",
      image_url: "/mango-branch.png",
      display_order: 3,
    },
  ],
  food_gallery: FOOD_GALLERY_IMAGES.map((img, i) => ({
    section_key: "food_gallery",
    item_key: `dish_${i + 1}`,
    title: `Specialty Dish ${i + 1}`,
    subtitle: "Craft Kitchen",
    image_url: img,
    display_order: i + 1,
  })),
  nature: AMBIENCE_IMAGES.map((img, i) => ({
    section_key: "nature",
    item_key: `ambience_${i + 1}`,
    title: `Cafe Ambience ${i + 1}`,
    subtitle: "Natural Oasis",
    image_url: img,
    display_order: i + 1,
  })),
  story: [
    {
      section_key: "story",
      item_key: "story_coffee",
      title: "The Coffee",
      subtitle: "SCA 85+ single origins and White Teak Cascara",
      image_url: "/scroll track/ChatGPT_Image_Apr_29__2026__03_03_11_PM-removebg-preview.png",
      display_order: 1,
    },
    {
      section_key: "story",
      item_key: "story_teas",
      title: "The Teas",
      subtitle: "Direct-from-farm single origins and craft blends",
      image_url: "/scroll track/ChatGPT_Image_Apr_29__2026__03_08_59_PM-removebg-preview.png",
      display_order: 2,
    },
    {
      section_key: "story",
      item_key: "story_bakes",
      title: "The Bakes",
      subtitle: "In-house craft kitchen comfort food",
      image_url: "/scroll track/ChatGPT_Image_Apr_29__2026__03_08_45_PM-removebg-preview.png",
      display_order: 3,
    },
    {
      section_key: "story",
      item_key: "story_home_brewing",
      title: "Home Brewing",
      subtitle: "Curated brewing equipment and slow rituals",
      image_url: "/scroll track/ChatGPT_Image_Apr_29__2026__03_11_42_PM-removebg-preview.png",
      display_order: 4,
    },
    {
      section_key: "story",
      item_key: "story_events",
      title: "Events",
      subtitle: "Shared spaces for artists, makers, and conversations",
      image_url: "/scroll track/ChatGPT_Image_Apr_29__2026__03_26_30_PM-removebg-preview.png",
      display_order: 5,
    },
  ],
  farm: FARM_IMAGES.map((img, i) => ({
    section_key: "farm",
    item_key: `plantation_${i + 1}`,
    title: `Estate Origin ${i + 1}`,
    subtitle: "From our founding estate",
    image_url: img,
    display_order: i + 1,
  })),
  feature_cards: FEATURE_CARDS.map((card, i) => ({
    section_key: "feature_cards",
    item_key: `feat_${i + 1}`,
    title: card.title,
    subtitle: card.subtitle,
    image_url: card.image,
    display_order: i + 1,
  })),
  categories: CATEGORY_LINKS.map((cat, i) => ({
    section_key: "categories",
    item_key: `cat_${cat.name.toLowerCase()}`,
    title: cat.name,
    subtitle: "Category",
    image_url: cat.image,
    display_order: i + 1,
  })),
  locations: [
    {
      section_key: "locations",
      item_key: "loc_gokulam",
      title: "Gokulam",
      subtitle: "7 AM – 11 PM",
      image_url: "/locations/wtcr_gokulam.webp",
      display_order: 1,
    },
    {
      section_key: "locations",
      item_key: "loc_kavi_mane",
      title: "Kavi Mane",
      subtitle: "11 AM – 9 PM",
      image_url: "/locations/kavi_mane.webp",
      display_order: 2,
    },
    {
      section_key: "locations",
      item_key: "loc_sainikpuri",
      title: "Sainikpuri",
      subtitle: "7 AM – Midnight",
      image_url: "/locations/sainikpuri.webp",
      display_order: 3,
    },
    {
      section_key: "locations",
      item_key: "loc_bengaluru",
      title: "Bengaluru",
      subtitle: "Brewing Soon",
      image_url: "",
      display_order: 4,
    },
  ],
  reels: [],
};
